import type { WorkspaceDocumentV4 } from '@neo-anki/compatibility-domain'
export type PromptVariant=string
export interface MediaAsset{id:string;filename:string;mimeType:string;dataUrl:string;bytes?:Uint8Array;byteLength:number;hash:string;altText:string;createdAt:string;updatedAt:string}
export interface KnowledgeItem{id:string;prompt:string;answer:string;context:string;collection:string;tags:string[];citations:Array<{id:string;title:string;url?:string}>;mediaIds:string[];occlusions:unknown[];createdAt:string;updatedAt:string}
export interface PracticeCard{id:string;itemId:string;variant:string;promptData?:Record<string,unknown>;suspended:boolean;fsrs:ReturnType<typeof makeEmptyFSRSCard>;estimatedSeconds:number;createdAt:string;updatedAt:string}
export interface ImportSummary{source:string;items:KnowledgeItem[];cards:PracticeCard[];assets:MediaAsset[];warnings:string[];preflight?:Record<string,unknown>}
export const createAssetFromBytes=async(filename:string,bytes:Uint8Array,altText='',mimeType='application/octet-stream'):Promise<MediaAsset>=>{const digest=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength) as ArrayBuffer))).map((value)=>value.toString(16).padStart(2,'0')).join(''),now=new Date().toISOString();return{id:`asset-${digest.slice(0,20)}`,filename,mimeType,dataUrl:'neoanki-media://pending',bytes,byteLength:bytes.length,hash:digest,altText,createdAt:now,updatedAt:now}}
export const makeEmptyFSRSCard=(now=new Date())=>({due:now.toISOString(),stability:0,difficulty:0,elapsed_days:0,scheduled_days:0,reps:0,lapses:0,state:0,last_review:undefined as string|undefined})
export const workspaceDocumentV4ToAppData=(document:WorkspaceDocumentV4)=>{const types=new Map(document.workspace.noteTypes.map((value)=>[value.id,value])),decks=new Map(document.workspace.decks.map((value)=>[value.id,value]));const items=document.workspace.notes.map((note)=>{const fields=(types.get(note.noteTypeId)?.fieldIds||[]).map((id)=>note.fields[id]||'');return{id:note.id,prompt:fields[0]||'',answer:fields[1]||fields[0]||'',context:fields.slice(2).join('\n'),collection:'Imported',tags:note.tags,citations:[],mediaIds:[],occlusions:[],createdAt:note.createdAt,updatedAt:note.updatedAt}});return{items,cards:document.workspace.cards.map((card)=>({id:card.id,itemId:card.noteId,variant:card.clozeOrdinal?'cloze':'forward',suspended:card.suspended,fsrs:makeEmptyFSRSCard(new Date(('dueAt'in card.scheduling&&card.scheduling.dueAt)||card.createdAt)),estimatedSeconds:14,createdAt:card.createdAt,updatedAt:card.updatedAt,deckName:decks.get(card.deckId)?.name})),assets:[]}}
